model_list:
  # Ollama Models
  - model_name: ollama-llama3.1
    litellm_params:
      model: ollama/llama3.1:latest
      api_base: http://ubuntu:11434
      api_key: none
  - model_name: gpt-5-nano
    litellm_params:
      model: openai/gpt-5-nano
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY


general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true
